### ISSUE TITLE
Add conversion of the "\r\n.\r\n" DATA terminator when it occurs in the message body

### ISSUE THREAD

**Issue by ionutradu** [mindbit/mailfilter#13]
The smtp_copy_to_file function (smtp_server.c) needs to "catch" every "\r\n..\r\n" that is contained in the message body and convert it to "\r\n.\r\n" to be written in the temporary file - where the message body is stored.

The smtp_copy_from_file function (smtp_client.c) needs to convert every "\r\n.\r\n" to "\r\n..\r\n" when sending the message on the socket.

**Comment by rrendec** [comment]
Fixed in 869bb13a5d5cf6aae2bbf43e0fa2c85aca83c97d and ee7052d61661d7de341e1e7534c745c3974c8bb9.
